### ISSUE TITLE
Ajout d'un accès Zeus pour les admins

### ISSUE THREAD

**Issue by ArwynFr** [lamuerta/DailyWarfare#1]

**Comment by ArwynFr** [comment]
Actuellement le Zeus est disponible pour le commandant.

**Comment by Stark91** [comment]
D'après le wiki de BIS, dans le module Zeus "Maître du jeu", tu peux préciser "server admin" (je suis pas sûr de ce qu'il faut marquer) dans le champ propriétaire.
[https://community.bistudio.com/wiki/Curator#Setup](url)

**Comment by ArwynFr** [comment]
Oui, c'est le changement que j'ai fait.
Ça fonctionne en multi, reste juste à tester sur le serveur.
