### ISSUE TITLE
Éjection des joueurs non connectés au TS

### ISSUE THREAD

**Issue by ArwynFr** [lamuerta/DailyWarfare#11]
Peut-on éjecter les joueurs qui ne sont pas connectés au TS ?
Peut-être sur le même mode de fonctionnement que le nomods ?

Par contre, je pense qu'il faudrait éviter d'exclure les joueurs connectés à TS sans TFAR.
Encore que ...

A discuter :)

**Comment by Stark91** [comment]
A discuter sur loomio peut-être, que ça serve à quelque chose...

**Comment by Stark91** [comment]
Sondage créé, lien sur le forum.

**Comment by ArwynFr** [comment]
Lien forum : https://forum.lamuerta.fr/viewtopic.php?f=9&t=837&p=7304#p7304
Loomio : https://loomio.lamuerta.fr/p/NJyCoWmO/ejection-des-joueurs-avec-tfar-d-sactiv-

**Comment by ArwynFr** [comment]
Décision : ne pas éjecter les joueurs.
Du coup on a mis un overlay qui demande aux joueurs de se connecter au TS : #13
