### ISSUE TITLE
Matériel de navigation manquant pour ingé et médic en chef

### ISSUE THREAD

**Issue by ImplicitDeny** [lamuerta/DailyWarfare#15]
Le matériel de navigation est manquant dans les slots d'ingénieur en chef et de médic en chef, dirigeant respectivement les groupes Echo et Foxtrot.

Ce manque est due au fait que les slots utilisés pour le personnel et le leader de ces deux groupes sont les mêmes, il n'existe pas de type "ingénieur en chef" dans le LMW. Par conséquent, la correction est spécifique à la Daily Warfare et doit être apportée au moyen d'un script approprié.

**Comment by Stark91** [comment]
Est-ce qu'il ne serait pas judicieux, à long terme, de créer un slot ingénieur en chef/docteur en chef avec le matériel adéquat dans LMW? Je dis bien à long terme. Un hotfix est plus logique pour l'instant car on a d'autres choses urgentes à régler.

**Comment by ImplicitDeny** [comment]
C'est possible mais quel intérêt ? C'est un cas particulier qu'un ingé ou un médic soient en tête d'un groupe.

**Comment by Stark91** [comment]
C'est ce que j'appelle le long terme. Pour l'instant on ne l'utilise que dans la DW, mais rien ne nous dit qu'on ne l'utilisera pas régulièrement par la suite. Dans ce cas de figure, c'est plus judicieux de travailler un peu plus à un moment pour éviter d'avoir à reprendre le slot x fois.

**Comment by ArwynFr** [comment]
Je pense que c'est un sujet à débattre.
Aujourd'hui, la question se pose car on n'a que 3 ingénieurs et que le chef de groupe est l'un d'eux.
A terme, Echo pourrait être un groupe de 4 ingénieurs + 1 opérateur radio + 1 chef de groupe soutien.

Idem pour Foxtrot.
