### ISSUE TITLE
Lévitation lorsqu'on s'asseoit sur une chaise

### ISSUE THREAD

**Issue by ArwynFr** [lamuerta/DailyWarfare#2]
Lorsqu'on s’assoit sur une chaise, le personnage apparait en lévitation au lieu d'être assis correctement.

**Comment by ArwynFr** [comment]
On pourrait corriger ce problème en remplaçant les chaises de camping par des chaises en bois.

**Comment by ArwynFr** [comment]
A priori le problème est causé par le mod Enhanced Movement quand il est utilisé avec ACEX Sitting et WMO. Peut-être qu'une mise à jour récente du mod pourrait corriger le problème ?

**Comment by ImplicitDeny** [comment]
Walkable Moving Object proposait une technologie qui a par la suite été intégrée dans Enhanced Movement. WMO n'est donc plus sensé faire partie de notre modpack. Toutefois si c'est lié à la technologie utilisée (qui n'a pas changé des stocks de WMO à EM) c'est logique que le bug soit présent. On va voir ce que les dernières MAJ de EM proposent, mais il a la mauvaise habitude de ne pas documenter ses updates.

**Comment by ArwynFr** [comment]
Visiblement c'est corrigé depuis la version du 07/05 :
https://forums.bohemia.net/forums/topic/174788-enhanced-movement/?page=45&tab=comments#comment-3289192

**Comment by Stark91** [comment]
Du coup, vous savez ce qui reste à faire : test et MàJ si concluant

**Comment by ArwynFr** [comment]
C'est confirmé, le bug est résolu par la mise à jour du mod enhanced movement.
