### ISSUE TITLE
Les panneaux de fréquence radio ne sont pas à jour

### ISSUE THREAD

**Issue by ArwynFr** [lamuerta/DailyWarfare#3]

**Comment by ImplicitDeny** [comment]
Pas de texture utilisable pour remplacer celle par défaut du panneau (lui-même implémenté dans l'un des PBO LM), donc les panneaux erronés ont tout simplement été retirés de la mission. Les fréquences actuellement en service restent consultables via le journal du joueur.

**Comment by ArwynFr** [comment]
Vu qu'on part sur des canaux à fréquence fixe, il faudrait mettre à jour le visuel dans le briefing aussi :)
