### ISSUE TITLE
Erreurs de script TFR

### ISSUE THREAD

**Issue by ImplicitDeny** [lamuerta/DailyWarfare#8]
Erreurs de scripts diverses sur le pré-réglage des radios au démarrage de la mission. Les fonctions ont du être modifiées entre temps, à corriger parce que c'est moche.

**Comment by ArwynFr** [comment]
Est-ce qu'on en profiterait pas pour passer a un plan de fréquences fixes ?
C'est à dire configurer toutes les radios avec les mêmes fréquences.
Comme ça les joueurs ont seulement besoin de change de canal (sauf usage spécifique).

Mais je pense qu'il faut en parler avec l'équipe avant de décider :)

**Comment by ImplicitDeny** [comment]
Les radios nous accordent 8 canaux, je pense que ça peut suffire à l'usage quotidien mais certaines soirées nécessiterons plus que ça. Je pense notamment à quand il y a des invités. Mais une planification attentive pourrait permettre de réduire les besoins de bricolage au strict minimum, aux cas les plus extrêmes. Surtout depuis que les véhicules disposent d'un intercom' et qu'il n'y a plus besoin de fréquences internes.

Donc, à voir, ça peut être intéressant. On lance une discu forum/loomio ?

**Comment by ImplicitDeny** [comment]
By the way, je n'ai pas réussi à régler l'erreur. Des fois elle apparait, des fois non. D'une ligne à l'autre c'est assez erratique. On dirait un genre d'exception contextuelle interne à TFR, c'est bizarre.
